login-workflow/CHANGELOG.md, login-workflow/example/ios/Podfile.lock, login-workflow/package.json, login-workflow/src/screens/ChangePassword.tsx, login-workflow/src/subScreens/CreatePassword.tsx
Fixes an issue where using custom password criteria would not allow you to progress to the next screen when creating an initial password during registration, or when changing your password.
- Remove the hardcoded password regex checks
- Replace the checks with checks for the custom criteria that are passed in
=> Fix password criteria on reset and register

login-workflow/CHANGELOG.md, login-workflow/example/ios/Podfile.lock, login-workflow/package.json, login-workflow/src/screens/InviteRegistrationPager.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx
Fixes #50.
- Use request animation frame to avoid crashing when completing self registration flow for an existing user
> I did not verify this on android, so if somebody could run through the four scenarios (invite-accountExists, invite-accountDoesNotExist, self-accountExists, self-accountDoesNotExist) to make sure they work, that would be great.
=> Fix crash on iOS

login-workflow/CHANGELOG.md, login-workflow/package.json, login-workflow/src/subScreens/Eula.tsx, login-workflow/src/subScreens/ResetPassword.tsx, login-workflow/src/subScreens/VerifyEmail.tsx
Fixes #84 
Fixes #86
- Fixes an issue where html EULA content is not displayed during registration (86) 
- Fixes an issue where the software keyboard blocks the input fields on forgot password screen (84)
- Refactors max width behavior on two screens to show how we want to fix 75 
**Input Issue**
- Run the demo project and go to the forgot password screen
- Trigger the software keyboard and confirm that the page is still scrollable and you can bring the input field into view
**EULA Issue**
- Follow the reproduction steps in the bug (set htmlEula to true and update registrationUIActions to return HTML content for the eula)
- Confirm that the HTML eula is displayed
=> Fix issue with html eula and keyboard blocking input

login-workflow/CHANGELOG.md, login-workflow/example/App.tsx, login-workflow/example/ios/Podfile.lock, login-workflow/example/ios/example/AppDelegate.m, login-workflow/package.json, login-workflow/src/__tests__/subscreens/AccountDetails-test.tsx, login-workflow/src/screens/InviteRegistrationPager.tsx, login-workflow/src/screens/Login.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx, login-workflow/src/subScreens/AccountDetails.tsx, login-workflow/yarn.lock
Fixes PXBLUE-2285, #83, and #90.
- Allow users to go back during all steps in the account registration workflows
- Changed EULA page order so it shows first during self registration
- Add ability to customize character limits for first and last name text fields
- Clear Invalid credentials error message after editing input
** Use shared-auth branch `feature/add-name-character-limits` to test these.
- Custom character limit, uncomment the registrationConfig definition in the `AuthUIContextProvider` in the example project's `App.tsx` file.
- Invalid credentials error message, edit the example project's `AuthUIActions.tsx `login method to immediately return `throw new Error('LOGIN.INVALID_CREDENTIALS');`. Start up example project and try to login. The "Invalid credentials" error should …
=> React Native workflow fixes

login-workflow/CHANGELOG.md, login-workflow/package.json, login-workflow/src/subScreens/Eula.tsx
Fixes an issue reported by CRDS team. The loading EULA screen uses light theme even if the application is set to dark theme.
- Set the background and font colors based on the theme
- Remove some default margin/padding
Before:
After:
- Open the example project
- In App.tsx, set htmlEula to true on the AuthUIContextProvider
- On the App component, set the theme to BLUITemes.blueDark
- In the loadEula function in RegistrationUIActions.tsx, make sure you are returning an HTML string for the EULA. You can use this as an example:
```tsx
export const SAMPLE_EULA_HTML = `
<style>
html, body{
margin: 0;
padding: 0;
background: #1d2529;
}
.eulaWraper {
background: #1d2529;
font-family: 'Open Sans';
font-family: 'OpenSans-Regular';
word-wrap: break-word;
}
.eulaWraper p,
.eulaWraper ul li {
color: …
```
=> Fix EULA colors for dark theme

login-workflow/example/ios/example/AppDelegate.m, login-workflow/example/ios/example/Info.plist, login-workflow/src/screens/SelfRegistrationPager.tsx, login-workflow/src/subScreens/VerifyEmail.tsx
Fixes #118 
- All PagerViews should be wrapped in a plain View and not use flex. As the others are fine at the moment, only the VerifyEmail screen was wrapped.
- Added some methods to App Delegate to allow deeplinks to work
- React Native Pager view is broken. You might need to test with the branch from this [PR](https://github.com/callstack/react-native-pager-view/pull/520)
- Deeplink command test from terminal when running in iOS sim. `xcrun simctl openurl booted "authui://register/696512?email=test%40domain.com"`
=> Fix empty code validation screen opened from link

login-workflow/src/__tests__/subscreens/CreateAccount-test.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx, login-workflow/src/subScreens/CreateAccount.tsx
- When coming from a deep link to self-registration, EULA should be already accepted and the email should be entered in case the user goes back.
- Wrap PagerView views in an empty view (no flex) to avoid over-optimization (resulting in "blank" pages).
React-Native-Pager-View might have to be changed to `https://github.com/Shiverware/react-native-pager-view.git` in order to fix some of the issues in the current pager release.
=> Fill eula and email on deeplink and wrap pages in views

login-workflow/CHANGELOG.md, login-workflow/example/ios/Podfile.lock, login-workflow/example/package.json, login-workflow/example/yarn.lock, login-workflow/package.json, login-workflow/src/subScreens/VerifyEmail.tsx, login-workflow/yarn.lock
BLUI-3269
Fixes #157 
- Verification code button style update
- Clone react-native-workflow project
- Initialize react-auth-shared submodule using branch `feature/3269-add-verification-code-prompt-translation-text`
- `yarn start:example`
- Go to self registration workflow (click debug button, then click self-registration button)
- Navigate to the third screen in the workflow to visit the verification code page
- Observe the updated view
=> Update resend verification code button styles

login-workflow/CHANGELOG.md, login-workflow/src/subScreens/Eula.tsx
Fixes #76 & BLUI-2964.
- Properly align Eula checkbox
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git`
- `git checkout feature/2964-center-eula-checkbox`
- start registration workflow
- observe eula checkbox is left aligned with the eula text
- be sure to check landscape as well
=> Properly align eula checkbox

login-workflow/CHANGELOG.md, login-workflow/example/ios/Podfile.lock, login-workflow/example/package.json, login-workflow/example/yarn.lock, login-workflow/package.json, login-workflow/src/components/RequirementCheck.tsx, login-workflow/src/screens/InviteRegistrationPager.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx, login-workflow/yarn.lock
Fixes #161 / BLUI-3220 .
- Use proper colors for MobileStepper and RequirementCheck active/valid state when using dark theme
Left: Before | Right: After
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git`
- `git checkout feature/BLUI-3220-mobile-stepper-pw-dark-theme-bug`
- update `example/App.tsx` line 262 to use the dark theme `{BLUIThemes.blueDark}`
- go to create account
- observe dot stepper showing the active state of which screen you are on
- step through to create password
- update password accordingly and observe the PasswordRequirements are being checked off with the proper color
=> BLUI-3220 MobileStepper and PasswordRequirement dark theme not showing proper active/valid state color

login-workflow/example/App.tsx, login-workflow/example/ios/Podfile.lock, login-workflow/example/package.json, login-workflow/example/yarn.lock, login-workflow/package.json, login-workflow/src/screens/Login.tsx, login-workflow/yarn.lock
Fixes #112 /BLUI-2778.
- add username login functionality
- Clone RN workflows repo
- Be sure you are using the following branch for the auth-shared submodule `feature/blui-2778-add-username-regex-and-translations`
- Uncomment line 83 of the example `App.tsx` file and run `yarn start:example`
- Observe username field and make sure you can log in using it
- The default is 'email', so be sure to test the explicit case where you set it to email and the case where you provide no value for the `loginType` prop on the `AuthUIContextProvider`
=> BLUI-2778 add username login functionality

login-workflow/CHANGELOG.md, login-workflow/example/android/app/src/main/AndroidManifest.xml
Fixes https://github.com/brightlayer-ui/react-native-workflows/issues/130 .
- update android manifest (android:windowSoftInputMode="stateAlwaysHidden|adjustPan")
- "stateAlwaysHidden" | The soft keyboard is always hidden when the activity's main window has input focus.
- "adjustPan" | The activity's main window is not resized to make room for the soft keyboard. Rather, the contents of the window are automatically panned so that the current focus is never obscured by the keyboard and users can always see what they are typing. This is generally less desirable than resizing, because the user may need to close the soft keyboard to get at and interact with obscured parts of the window.
- switch shared auth to dev
- yarn start:example-android
- select any input field and notice keyboard remains …
=> fix bug blui 3309 keyboard

login-workflow/CHANGELOG.md, login-workflow/example/ios/Podfile.lock, login-workflow/src/screens/InviteRegistrationPager.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx, login-workflow/src/subScreens/AccountDetails.tsx, login-workflow/src/subScreens/Eula.tsx, login-workflow/src/subScreens/ResetPassword.tsx
Fixes #75 & BLUI-2965.
Fixes #164 as well.
- Make scroll containers fill the screen 
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git`
- `git checkout feature/blui-2965-fix-scroll-container`
- `yarn start:example-ipad`
- If the ipad script doesn't work update the example script for ipad to suit your local environment needs
- check all workflows and ensure that you can scroll from anywhere, not just the inner 600px of content
Disclaimer: I need to and have yet to thoroughly test this tested across all devices so I'll be manually testing further on physical devices and android while this PR is open. Just want to get eyes on it sooner than later in case there are issues.
I will write another story to address the alignment of the checkbox button for the EULA page as well. …
=> BLUI-2965 Fix scroll container

login-workflow/docs/customization.md, login-workflow/example/ios/Podfile.lock, login-workflow/example/src/screens/CustomRegistrationForm.tsx, login-workflow/example/yarn.lock, login-workflow/src/screens/InviteRegistrationPager.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx
Fixes #73 & BLUI-2966.
- Fix keyboard next button for navigating between default account details and custom account details
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git -b feature/blui-2966-fix-keyboard-next-button-with-refs`
- `cd react-native-workflows/login-workflow`
- `yarn initialize`
- `cd shared-auth && git checkout feature/blui-2966-fix-keyboard-next-button-with-refs`
- `cd .. && yarn start:example`
- check both "Invite Register" and "Self Register" flows to ensure that you can navigate between pages and form fields using the native keyboard next buttons.
Note: There's a weird bounce that happens when moving to the 3rd and 4th input fields. I've checked this and it's an issue across the board if the form extends below the keyboard. If we want this fixed …
=> BLUI-2966 Fix keyboard next button with refs

login-workflow/CHANGELOG.md, login-workflow/example/App.tsx, login-workflow/example/ios/Podfile.lock, login-workflow/package.json, login-workflow/src/__tests__/screens/Login-test.tsx, login-workflow/src/screens/Login.tsx, login-workflow/yarn.lock
Fixes #124 & BLUI-2968.
- Add ability to customize how login error messages are displayed
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git -b feature/blui-2968-login-error-display-config`
- `cd react-native-workflows/login-workflow`
- Modify example `AuthUiActions.tsx` login method to immediately return an error (e.g., `throw new Error('LOGIN.INVALID_CREDENTIALS');` || `throw new Error('error message...');`)
- Add a loginErrorDisplayConfig to the example `App.tsx` (see examples below)
- `yarn start:example`
- Observe various error message configs
example configs
` loginErrorDisplayConfig={{ mode: 'dialog' }}`
`loginErrorDisplayConfig={{ mode: 'message-box', position: 'top' }}`
`loginErrorDisplayConfig={{ mode: 'message-box', position: 'bottom' }}` …
=> BLUI-2968 - Add login error message configuration functionality

login-workflow/example/App.tsx, login-workflow/example/ios/Podfile.lock, login-workflow/src/screens/ChangePassword.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx, login-workflow/src/subScreens/CreateAccount.tsx
Fixes #75 & BLUI-2965.
- Make scroll containers fill the screen for registration workflow email screen and the change password success screen
- `git clone git@github.com:brightlayer-ui/react-native-workflows.git -b feature/blui-2965-fix-scroll-container`
- `yarn start:example-ipad`
- If the ipad script doesn't work update the example script for ipad to suit your local environment needs
- check self registration workflow email screen and the change password success screen and ensure that you can scroll from anywhere, not just the inner 600px of content
=> BLUI-2965 - Cleanup: Fix scroll width on registration workflow and change password success screen

login-workflow/CHANGELOG.md, login-workflow/package.json, login-workflow/src/screens/AuthNavigationContainer.tsx, login-workflow/src/screens/ChangePassword.tsx
Fixes #121 BLUI-3648
- Added Change password screen outside AuthUIInternalStore
https://user-images.githubusercontent.com/25982779/206149720-da57e147-d389-4082-a416-98c5b57e0565.mov
- cd login-workflows
- Navigate to Page One or Page Two 
- Open User Settings on right top
- Open Change Password
- Press Close(X) or Cancel button
=> Fixed Change password back route

login-workflow/LICENSES.json, login-workflow/package.json, login-workflow/src/screens/InviteRegistrationPager.tsx, login-workflow/src/screens/Login.tsx, login-workflow/src/screens/SelfRegistrationPager.tsx, login-workflow/src/subScreens/AccountDetails.tsx, login-workflow/yarn.lock
- Mimmic the hotfix from the React workflow package
- Allow hiding of the create password screen
You will probably need to disable hermes in the Podfile of the example in order to run (I did)
And disable the password screen in App.tsx to see the effect
=> [HOTFIX] Allow hiding the create password screen

.circleci/config.yml, login-workflow/codecov.yml
Fixes Blui-5158.
- add step to install, prettier & lint
- add step to test with parallelism: 4 & store test results
- edit workflow to include test
https://app.codecov.io/gh/etn-ccis/blui-react-native-workflows/tree/feature%2Fblui-5158-divide-build-steps/login-workflow%2Fsrc
-
-
=> Clean up the CircleCI Build Pipeline for RN workflow

login-workflow/package.json, login-workflow/setup-tests.js, login-workflow/yarn.lock
Fixes BLUI-5239.
- Remove Enzyme, types and adapters
- Update test setup
-
-
- checkout branch
- install dependencies
- yarn test
- snapshot test options (can run either or)
```
// snapshot test using react-test-renderer & jest
test('renders correctly', () => {
const tree = renderer.create(
<WorkflowCardBody>
<Text>This is workflow card body content.</Text>
</WorkflowCardBody>
).toJSON();
expect(tree).toMatchSnapshot();
});
//   snapshot test using @testing-library/react-native & jest
test('renders correctly', () => {
const tree = render(
<WorkflowCardBody>
<Text>This is workflow card body content.</Text>
</WorkflowCardBody>
)
expect(screen.toJSON()).toMatchSnapshot()
});
```
=> Blui 5239 update test config & remove enzyme

login-workflow/docs/components/basic-dialog.md, login-workflow/package.json, login-workflow/src/__tests__/components/Dialog/BasicDialog-test.tsx, login-workflow/src/components/Dialog/BasicDialog.tsx, login-workflow/src/components/Dialog/index.tsx, login-workflow/src/components/index.tsx, login-workflow/yarn.lock
Fixes # BLUI-5214
- Added Basic dialog component
- Added documentation
- Add test cases
- 
For Testing, please update the existing WorkflowCardBody in the example with 
`<WorkflowCardBody>
<>
<BasicDialog
title={'Error!'}
body={'Error Body'}
open={hasError}
onDismiss={() => setHasError(false)}
/>
<TextInput
label="TextInput"
mode="flat"
left={<TextInput.Icon icon="email" />}
right={<TextInput.Icon icon="menu-down" />}
value={errorFilledText}
underlineColor={theme.colors.surface}
onChangeText={(value: string): void => {
setErrorFilledText(value);
setHasError(value.length > 4);
}}
error={hasError}
/>
<HelperText type="error" visible={hasError} style={{ marginBottom: 8 }}>
Error Message
</HelperText>
</>
</WorkflowCardBody>`
- cd login-workflows
- Click on Workflow Card …
=> Feature/5213 implement Basic Dialog 

login-workflow/src/components/WorkflowCard/WorkflowCardHeader.tsx
Fixes 5340 .
- height should be updated to 64px
- Default background color should be the lighter blue color (refer to what we used in Header)
- On tablet (when in a card), theCardHeader background should match the background of the card and the text should be the darker default text color.
- GO to workflow card example and check font, color, background color of  title, and subtitle as per [Figma](https://www.figma.com/file/Nydz8n8HBj6U3ZtULja3gD/%F0%9F%92%AB-Brightlayer-UI-Tokens-%2B-Components-(in-Material-Design-3)?type=design&node-id=417-3219&mode=design&t=XRIUIGYColAsbP4g-0) 
-
=> Update header styles

login-workflow/src/contexts/RegistrationContext/RegistrationDictionaries/chinese.ts, login-workflow/src/contexts/RegistrationContext/RegistrationDictionaries/french.ts, login-workflow/src/contexts/RegistrationContext/RegistrationDictionaries/portuguese.ts, login-workflow/src/contexts/RegistrationContext/RegistrationDictionaries/spanish.ts
Fixes # BLUI-5498
We miss this in https://github.com/etn-ccis/blui-react-native-workflows/pull/387
- Updated other language success screen translations with bold tag
- 
- cd login-workflows
- Change the language to other than English
- Open drawer
- Press Registration Provider Example
- Go through registration process to see the success screen
- Email and organisation name should be bold
-
=> Updated success screen translations with bold tag

login-workflow/example/ios/example.xcodeproj/project.pbxproj, login-workflow/example/src/screens/RegistrationProviderExample.tsx, login-workflow/src/components/RegistrationWorkflow/RegistrationWorkflow.tsx, login-workflow/src/constants/index.ts, login-workflow/src/screens/AccountDetailsScreen/AccountDetailsScreen.tsx, login-workflow/src/screens/ContactScreen/ContactSupportScreen.tsx, login-workflow/src/screens/CreateAccountScreen/CreateAccountScreen.tsx, login-workflow/src/screens/CreateAccountScreen/CreateAccountScreenBase.tsx, login-workflow/src/screens/CreatePasswordScreen/CreatePasswordScreen.tsx, login-workflow/src/screens/EulaScreen/EulaScreen.tsx, login-workflow/src/screens/ExistingAccountSuccessScreen/ExistingAccountSuccessScreen.tsx, login-workflow/src/screens/RegistrationSuccessScreen/RegistrationSuccessScreen.tsx, login-workflow/src/screens/VerifyCodeScreen/VerifyCodeScreen.tsx, login-workflow/src/screens/VerifyCodeScreen/VerifyCodeScreenBase.tsx
Fixes #BLUI-5524 .
- Added setTimeout when `loading` is setting false.
-
-
-
-
- Please add your feedback on whether this code changes need to be merged or not, since these [code changes](https://github.com/etn-ccis/blui-react-native-workflows/pull/432/files) reduced showing the previous screen, but still we can see it.
=> Clicking on the next button in the registration workflow shows the previous screen and drawer for a fraction of a second

login-workflow/example/src/components/UserMenuExample.tsx, login-workflow/example/translations/dictionary/chinese.ts, login-workflow/example/translations/dictionary/english.ts, login-workflow/example/translations/dictionary/french.ts, login-workflow/example/translations/dictionary/portuguese.ts, login-workflow/example/translations/dictionary/spanish.ts, login-workflow/example/translations/dictionary/types.ts
Fixes #5718
- Add translations to the user menu list items as per language.
-
-
-
=> User menu Item Translate

login-workflow/CHANGELOG.md, login-workflow/docs/screens/login.md, login-workflow/src/screens/LoginScreen/LoginScreen.tsx, login-workflow/src/screens/LoginScreen/LoginScreenBase.tsx, login-workflow/src/screens/LoginScreen/types.ts
Fixes # .
- Fixed cybersecurity image size configuration issue. 
- Added prop for adding height and width to make cybersecurity image confiugurable
- Changes flex direction to align item to the center
-
- Run command start:example-android 
- Open file Login.tsx
- Add prop cyberSecurityBadgeSize={{height: 160, width: 150}} in LoginScreen component to add custom height & width
`
<LoginScreen
projectImage={
<Image
style={{ width: '100%' }}
resizeMode="contain"
source={require('../assets/images/eaton_stacked_logo.png')}
/>
}
header={<DebugComponent />}
cyberSecurityBadgeSize={{height: 160, width: 150}}
/>
`
-
=> Cybersecurity image size configuration

login-workflow/CHANGELOG.md, login-workflow/README.md, login-workflow/package.json
=> Screenshot changed

login-workflow/CHANGELOG.md, login-workflow/package.json, login-workflow/src/screens/LoginScreen/LoginScreen.tsx, login-workflow/src/screens/LoginScreen/LoginScreenBase.tsx
Fixes https://github.com/etn-ccis/blui-react-native-workflows/issues/514.
- Fixed keyboard dismiss error on login screen
To test -->
- Run yarn start:example-android
- Open index.tsx under navigation folder and replace OktaLogin with Login
=> Fixed login keyboard dismiss error on login click
