login-workflow/README.md
login-workflow/docs/existing-project-integration.md
login-workflow/docs/sample-project-integration.md
login-workflow/example/yarn.lock
login-workflow/package.json

Changes proposed in this Pull Request:
- Replace relative links with absolute ones so they will work on NPM
- Bump the package version
https://www.npmjs.com/package/@pxblue/react-native-auth-workflow/v/1.0.1-beta.1

Add media to npm

---

.gitmodules
login-workflow/.eslintignore
login-workflow/.prettierignore
login-workflow/CHANGELOG.md
login-workflow/LICENSES.json
login-workflow/example/ios/Podfile.lock
login-workflow/package.json
login-workflow/scripts/initializeSubmodule.sh
login-workflow/scripts/linkWorkflow.sh
login-workflow/src/components/DismissKeyboardView.tsx
login-workflow/src/components/LoginHeaderSplash.tsx
login-workflow/src/index.ts
login-workflow/src/screens/InviteRegistrationPager.tsx
login-workflow/src/screens/SelfRegistrationPager.tsx
login-workflow/src/screens/Splash.tsx
login-workflow/src/translations/i18n.ts
login-workflow/yarn.lock

- Move DismissKeyboardView and i18n object from the shared auth repository
NOTE: Need to update the dependency from beta once the shared auth PR is merged and a full version is published

Port RN specific elements from shared auth

---

login-workflow/example/ios/Podfile.lock
login-workflow/src/subScreens/VerifyEmail.tsx
login-workflow/src/translations/i18n.ts

Fixes #25.
- Include french (france) locale

Use french language for French (France) locale

---

login-workflow/example/ios/Podfile.lock
login-workflow/src/screens/Login.tsx
login-workflow/src/subScreens/CreateAccount.tsx
login-workflow/src/subScreens/ResetPassword.tsx

Fixes #38.
- Validate email inputs on blur

Validate email on blur

---

login-workflow/CHANGELOG.md
login-workflow/LICENSES.json
login-workflow/example/ios/Podfile.lock
login-workflow/package.json
login-workflow/src/screens/InviteRegistrationPager.tsx
login-workflow/src/screens/SelfRegistrationPager.tsx

Publishes the crash fix for iOS
- Use requestanimationframe to avoid crashing when going to the success screen on ioOS

Publish 3.0.1

---

login-workflow/LICENSES.json
login-workflow/example/ios/Podfile.lock
login-workflow/package.json
login-workflow/src/screens/ChangePassword.tsx
login-workflow/yarn.lock

Fixes #56 
- Update function call so that the event argument of the click handler is not passed as the first argument to the onUserNotAuthenticated function.
- Update dependency for shared auth
- Update submodule pointer to latest dev

Fix bug on remember me

---

login-workflow/CODEOWNERS

Add codeowners

---

CODEOWNERS
login-workflow/CODEOWNERS

- Move file to correct folder, add codeowner

Add codeowner

---

login-workflow/CHANGELOG.md
login-workflow/LICENSES.json
login-workflow/package.json
login-workflow/src/translations/i18n.ts
login-workflow/yarn.lock

For PXBLUE-1950
- Add spanish translations to i18n initializer

Support Spanish Translations

---

.circleci/config.yml
login-workflow/codecov.yml
login-workflow/package.json
login-workflow/yarn.lock

- add codecov and configs with codecod yml
- 
- 
https://app.codecov.io/gh/pxblue/react-native-workflows

initial codecov config with codecov yml

---

login-workflow/example/App.tsx
login-workflow/example/ios/Podfile.lock
login-workflow/example/src/components/TextInput.tsx
login-workflow/example/src/screens/CustomRegistrationForm.tsx
login-workflow/src/translations/i18n.ts

- Add the custom registration field examples back into the demo

Add the custom registration examples back

---

login-workflow/src/subScreens/Eula.tsx

- Fix Eula horizontal overflow issue

Fix eula overflow bug

---

login-workflow/README.md
login-workflow/src/subScreens/Eula.tsx

- Fixes links to point to RN instead of R

Fix Incorrect Links

---

login-workflow/CHANGELOG.md
login-workflow/example/ios/Podfile.lock
login-workflow/example/yarn.lock
login-workflow/package.json
login-workflow/src/screens/SelfRegistrationPager.tsx

Fixes #81 .
- Updated demo dependencies
- Tested a bunch of stuff to get this working
- Simplest solution was to introduce a View wrapper element around the Eula in the Self Registration Pager
- Ultimately this seems related to a bug in the react-native-pager-view. On it's own it seems fine, but there's some combination with our other dependencies that it doesn't seem to always play nice with.
- Another solution that worked was disabling the animation between successive screens, but I didn't want to have to do that and the View wrapper seems to work fine.
If you want to see it broken:
- Clone the dev branch
- cd react-native-workflows/login-workflow/demo
- yarn upgrade
- cd ..
To see it fixed:
- Clone this branch
- Run the example
- Click through the self registration …

Fix issue with EULA not showing

---

.circleci/config.yml
login-workflow/package.json

- Add automatic tagging command to circleCI
Putting this in before merging the patch version to see if it works.

Add automatic tagging

---

login-workflow/CHANGELOG.md
login-workflow/example/App.tsx
login-workflow/example/ios/Podfile.lock
login-workflow/example/package.json
login-workflow/example/yarn.lock
login-workflow/package.json

Fixes PXBLUE-2518.
- Prepare to publish 4.0.0
- Updated example project to use most up-to-date brightlayer-ui packages

Prep to publish 4.0.0

---

login-workflow/src/components/SimpleDialog.tsx
login-workflow/src/screens/ChangePassword.tsx
login-workflow/src/screens/ContactSupport.tsx

Fixes PXBLUE-2518.
- Fix typing errors
Test example project with react-auth-shared branch `feature/2518-blui-rebrand-fix-type-errors`

Fix typing errors

---

login-workflow/CHANGELOG.md
login-workflow/package.json
login-workflow/yarn.lock

Update changelog date and use latest beta package

Update changelog date and use latest beta package

---

login-workflow/package.json
login-workflow/yarn.lock

Use latest react-auth-shared package

Use latest react-auth-shared package

---

.gitmodules
login-workflow/example/ios/Podfile.lock

Update submodule pointer

---

login-workflow/package.json

Fixes # .
- add keyword section to package.json for view on NPM
- 
- 
-

add keywords

---

login-workflow/CHANGELOG.md
login-workflow/package.json

- Update package.json and changelog

Update version and changelog

---

login-workflow/README.md

Fixes # .
- add code cov badge to readme
- 
- 
-

add codecov badge

---

login-workflow/android/app/build.gradle
login-workflow/package.json
login-workflow/src/components/CloseHeader.tsx
login-workflow/src/components/IconSplash.tsx
login-workflow/src/components/RequirementCheck.tsx
login-workflow/src/index.ts
login-workflow/src/screens/InviteRegistrationPager.tsx
login-workflow/src/screens/SelfRegistrationPager.tsx
login-workflow/src/subScreens/ResetPasswordConfirm.tsx
login-workflow/src/subScreens/ResetPasswordSuccess.tsx
login-workflow/tsconfig.json

Fix some theme-related warnings during build
- Update theme color usage to reflect the newer theme syntax (no more primaryBase)
- Tell tsc not to build the example folder when building the workflow package

Fix theme types

---

login-workflow/VALIDATION.md

- Add `VALIDATION.md` file, same as angular-workflows just with updated test count & Portuguese test.

Add validation md file

---

login-workflow/CHANGELOG.md
login-workflow/docs/language-support.md
login-workflow/example/App.tsx
login-workflow/example/ios/Podfile.lock
login-workflow/example/package.json
login-workflow/example/yarn.lock
login-workflow/package.json
login-workflow/src/translations/i18n.ts
login-workflow/yarn.lock

Fixes #110 & BLUI-2962 .
- Add support for Portuguese
- replace line 33 in the example apps `App.tsx` with `void i18n.changeLanguage('pt');`
- `yarn start:example`
- observe text is all translated to Portuguese

Add portuguese translation config

---

login-workflow/src/screens/InviteRegistrationPager.tsx
login-workflow/src/screens/SelfRegistrationPager.tsx

Fixes BLUI-3220.
-  remove stepper color override

BLUI-3220 remove stepper color override

---

login-workflow/example/App.tsx

Fixes #55 & BLUI-2967.
- Update custom success screen styles
- Run the example project and walk through either of the registration workflows. The final screen will be the custom success screen with updated styles. Ensure that it matches the screenshot provided.

BLUI-2967 custom success screen styles

---

login-workflow/package.json
login-workflow/src/components/ToggleButton.tsx
login-workflow/src/screens/Login.tsx

- Adds test IDs and accessibility labels to the ToggleButton and Login components. This allows this elements to be easily testable via Appium and other test automation platforms.

Add test IDs and accessibility labels.

---

login-workflow/package.json
login-workflow/src/components/SimpleDialog.tsx
login-workflow/src/screens/Login.tsx
login-workflow/src/screens/SelfRegistrationPager.tsx

- Center dialog, errorMessage, and AccountDetails for selfRegistration
- Ensure the keyboard next button works
- Test this on as many devices as possible...
- Ensure that everything is looking nice on phone and tablet in regards to the issues in milestone 4.2.0

v4.2.0 Cleanup - Center dialog, errorMessage, and AccountDetails for selfRegistration

---

login-workflow/CHANGELOG.md
login-workflow/package.json

Update version and publish date

Update version and publish date

---

login-workflow/CHANGELOG.md
login-workflow/example/ios/Podfile.lock
login-workflow/example/yarn.lock
login-workflow/package.json
login-workflow/src/subScreens/AccountDetails.tsx
login-workflow/src/subScreens/CreateAccount.tsx
login-workflow/yarn.lock

Prepare to publish v5.0.0

---

login-workflow/CHANGELOG.md
login-workflow/package.json
login-workflow/src/screens/ChangePassword.tsx

Fixes #121  BLUI-3648
- Added position and with to change password success screen
- cd login-workflows

Addeed position absolte and width

---

login-workflow/src/screens/ChangePassword.tsx

Fixes #207 
- Added bottom style for change password screen

Added safe area view to change password screen

---

.gitmodules
CODEOWNERS
login-workflow/CHANGELOG.md
login-workflow/LICENSES.json
login-workflow/README.md
login-workflow/docs/API.md
login-workflow/docs/customization.md
login-workflow/docs/existing-project-integration.md
login-workflow/docs/language-support.md
login-workflow/docs/sample-project-integration.md
login-workflow/docs/theme-support.md
login-workflow/example/src/screens/home.tsx
login-workflow/package.json

- Updated all links to their GHE equivalences
- Updated Codeowners

Update codeowners and GHE links

---

login-workflow/README.md

Fixes #216 
- Replaced pxblue in images links with brightlayer-ui in Readme
-
- Clone the repo
- Go to readme.md
- Open media links line 13 to 17
-

Replcaed pxblue refs with brightlayer-ui in Readme

---

login-workflow/CHANGELOG.md
login-workflow/src/screens/ChangePassword.tsx

Fixes #210 
- Removed Cancel button on Change Password screen
- Updated changelog
- yarn build 
- cd example
- yarn ios
-

Removed cancel button in change password screen

---

login-workflow/CHANGELOG.md
login-workflow/package.json

- Updated package version to v5.1.0
- Updated changelog

Updated the package version and changelog

---

.circleci/config.yml
login-workflow/package.json
login-workflow/yarn.lock

Fixes BLUI-3627.
- use latest codecov and prep report
- remove old codecov dependency
- re-activate report
- badge link correct
- fix this
-
-

use latest codecov & badge link verified

---

login-workflow/CHANGELOG.md

Remove random /

---

login-workflow/README.md

- add missing build badge
-
-
-
-
-

add missing build badge

---

login-workflow/docs/language-support.md

List Portuguese as supported language

---

login-workflow/CHANGELOG.md
login-workflow/LICENSES.json
login-workflow/package.json
login-workflow/src/screens/Login.tsx
login-workflow/yarn.lock

- Allow hiding of the login form in the Login screen

HOTFIX: Allow hiding the login form in login screen

---

login-workflow/CHANGELOG.md
login-workflow/src/screens/SelfRegistrationPager.tsx

Fixes #280 BLUI-4724
- Reset verification code field value on next, back and resend button click
https://github.com/etn-ccis/blui-react-native-workflows/assets/120575281/998526bb-5162-4dc5-9b46-e4baa4347a57
- Click on Register Now button
- Go through the flow till Verify Email screen
- Enter any valid value in the input field
- Click on Resend, Back or Next to see the field value is reset
-

Fixed verification code prefilled issue on navigation

---

login-workflow/CHANGELOG.md
login-workflow/package.json

Fixes BLUI-4727.
- Update package version to `5.2.0-alpha.0` 
-
-
-
- **After Merging this branch into `release/6.0.0` will raise PR against dev branch for publishing alpha package.**

update package version for publishing

---

login-workflow/CHANGELOG.md
login-workflow/package.json

Fixes 4727.
- Update release date in changelog
- Update package version
-
-
-
-

Update package Version

---

login-workflow/CHANGELOG.md

update package 5.2.0 release date to today's date
-
-
-
-
-
-

update package 5.2.0 release date

---

login-workflow/CHANGELOG.md

fix changelog date

---

.circleci/config.yml
login-workflow/codecov.yml

Fixes Blui-5158. Divide circleCI build step
- Add config back
- Not running tests or coverage in CI until its ready
-
-
-
-
-

Blui 5158 divide build step

---

login-workflow/src/components/WorkflowCard/WorkflowCardInstructions.tsx

Fixes # Added js doc for workflow card instruction props
- Added js doc for workflow card instruction props
-
-
-

Added js doc for workflow card instruction props

---

.circleci/config.yml
login-workflow/.husky/pre-commit

Fixes Blui-5096.
- update pre-commit to use prettier:check
- turn tests on in CI and upload report
-
-
-
https://app.codecov.io/gh/etn-ccis/blui-react-native-workflows/tree/fix%2Fhook-prettier
-

Fix hook prettier

---

login-workflow/docs/components/workflow-card.md
login-workflow/src/components/WorkflowCard/WorkflowCard.types.ts
login-workflow/src/components/WorkflowCard/WorkflowCardActions.tsx

Add stepperVariant prop in WorkflowCardActions
-
-
-
- 
- Check workflowCardExample and observe WorkflowCardActions
-

Add stepperVariant prop in WorkflowCardActions

---

login-workflow/docs/components/workflow-card.md
login-workflow/docs/registration-workflow.md
login-workflow/src/contexts/RegistrationWorkflowContext/types.ts

Fixes # .
- Fix workflow docs
-
-
-
-
-

Fix readme for workflow

---

login-workflow/src/components/SetPassword/SetPassword.tsx

Fixes # .
password not showing error in case of no requirement are passed
-
-
-
-
- use the following code in example to test it
<SetPassword
onSubmit={() => {
// eslint-disable-next-line
console.log('submitted');
}}
confirmRef={confirmRef}
passwordRequirements={[]}
/>
-

fixed regex issue - SetPassword

---

login-workflow/example/src/screens/RegistrationSuccessScreen.tsx

Fixes # 
Fixed success screen icon color
- Fixed success screen icon color
- 
-
-

Fixed success screen icon color

---

login-workflow/docs/language-support.md

Fixes 5144 .
- update i18n guide
-
-
-
- check **login-workflow/docs/language-support.md**
-

update i18n guide

---

login-workflow/docs/registration-workflow.md
login-workflow/example/src/screens/RegistrationProviderExample.tsx

Fixes #BLUI-5145 .
- Updated RegistrationWorkflow Guide
-
- Please check, **login-workflow/docs/registration-workflow.md**
-

[Documentation] Write RegistrationWorkflow Guide

---

login-workflow/example/src/screens/RegistrationProviderExample.tsx
login-workflow/src/screens/EulaScreen/EulaScreen.tsx

Fixes # .
fixed the language change in Eula content
-
-
-
-
-
-

Eula full screen language fix

---

login-workflow/src/components/WorkflowCard/WorkflowCardHeader.tsx

Fixes # .
fixed status bar color in tablet
-
-
-
-
-
-

status bar color fix for tablet

---

login-workflow/README.md

Fixes BLUI-5469 .
- update read me file
-
-
-
-

Update main readme

---

login-workflow/docs/components/error-manager.md

Fixes # BLUI-5489 #369 
- Updated backgroundColor and fontColor default values in error manager api tables
- 
-
-

Removed default values for fontColor backgroundColor from api table

---

login-workflow/src/components/WorkflowCard/WorkflowCardHeader.tsx

Fixes https://github.com/etn-ccis/blui-react-native-workflows/issues/351.
- update workflowCard headerContent margin left to 16
-
-
- before
-after
-
-

Update header content space

---

login-workflow/docs/authentication-workflow.md
login-workflow/example/src/actions/AuthUIActions.tsx
login-workflow/example/src/components/AuthCustomScreen.tsx
login-workflow/example/src/constants/index.ts
login-workflow/example/src/contexts/AppContextProvider.tsx
login-workflow/example/src/navigation/index.tsx
login-workflow/example/src/navigation/navigation-drawer.tsx
login-workflow/example/src/screens/AuthProviderExample.tsx
login-workflow/example/src/screens/index.tsx
login-workflow/example/src/store/local-storage.ts
login-workflow/src/__tests__/contexts/AuthContextProvider-test.tsx
login-workflow/src/components/Error/types.ts
login-workflow/src/contexts/AuthContext/AuthDictionaries/chinese.ts
login-workflow/src/contexts/AuthContext/AuthDictionaries/english.ts
login-workflow/src/contexts/AuthContext/AuthDictionaries/french.ts
login-workflow/src/contexts/AuthContext/AuthDictionaries/index.ts
login-workflow/src/contexts/AuthContext/AuthDictionaries/portuguese.ts
login-workflow/src/contexts/AuthContext/AuthDictionaries/spanish.ts
login-workflow/src/contexts/AuthContext/AuthDictionaries/types.ts
login-workflow/src/contexts/AuthContext/context.ts
login-workflow/src/contexts/AuthContext/i18nAuthInstance.ts
login-workflow/src/contexts/AuthContext/index.ts
login-workflow/src/contexts/AuthContext/provider.tsx
login-workflow/src/contexts/AuthContext/types.ts
login-workflow/src/contexts/index.tsx
login-workflow/src/testUtils/index.ts

Fixes # BLUI-5117
- Added auth context, provider, hook
- Added test cases
- Added example
- 
- Added console to see email in `forgotPassword` in AuthUIActions
- Open drawer
- Press Auth Provider
- Check the console
-

Added auth context

---

login-workflow/docs/components/error-manager.md
login-workflow/src/components/Error/ErrorManager.tsx
login-workflow/src/components/Error/types.ts
login-workflow/src/components/RegistrationWorkflow/RegistrationWorkflow.tsx
login-workflow/src/contexts/RegistrationContext/provider.tsx

Fixes #BLUI-5471 .
- Updated ErrorManager component
-
-
-

Update ErrorManager to be a controlled component

---

login-workflow/docs/routing.md

Fixes # .
- Added documentation for Routing 
-
-
-
-
-

Routing guide

---

login-workflow/src/screens/VerifyCodeScreen/VerifyCodeScreenBase.tsx

Fixes BLUI-5495.
- Use react-native text component and style resend label
-
-
-
- git checkout feature/blui-5495-style-resend
- yarn start:example-ios (start:example-android)
- select registration provide example link
- accept EULA, enter email
- verify resend label
-

Style resend label

---

login-workflow/CHANGELOG.md

Fixes BLUI-5508.
- Update change log with user reported issues
- Issues opened/closed by BLUI
https://github.com/etn-ccis/blui-react-native-workflows/issues/209 Fixed - no build errors found (CLOSED ISSUE)
https://github.com/etn-ccis/blui-react-native-workflows/issues/198 Fixed - RCTBridge issue (CLOSED ISSUE)
https://github.com/etn-ccis/blui-react-native-workflows/issues/196 Fixed - enzyme no longer exists (CLOSED ISSUE)
https://github.com/etn-ccis/blui-react-native-workflows/issues/165 Fixed - in new architecture. (CLOSED ISSUE)
https://github.com/etn-ccis/blui-react-native-workflows/issues/167 Fixed - in new architecture. (CLOSED ISSUE)
https://github.com/etn-ccis/blui-react-native-workflows/issues/183 Fixed - in new architecture. (CLOSED ISSUE) …

Update change log fixes

---

login-workflow/example/src/screens/ContactBaseExample.tsx
login-workflow/src/screens/ContactScreen/ContactSupportScreenBase.tsx

Fixes # .
Updated the styling for the icon
-
-
-
-
-
-

contact base style fix

---

login-workflow/CHANGELOG.md

Fixes # .
- add issue #265 and #279 to fixed in changelog
-
-
-
-
-

Add fixed for 265 & 279

---

login-workflow/docs/integration.md

Fixes #BLUI-5521
-Adding [integration.md](http://integration.md/) file (linked from main workflow readme). 
-Followed React Workflow for template.
-
-
-

adding integration file

---

login-workflow/src/components/RegistrationWorkflow/RegistrationWorkflow.tsx

Fixes 5530.
- fix keyboard dismiss in workflow
- 
-
-
- Test registration workflow on Android and iOS
-

fix keyboard dismiss in workflow

---

login-workflow/src/screens/EulaScreen/EulaScreenBase.tsx

Fixes #BLUI-5533
- Fixed the font of Eula's content
-Checkbox is aligned to Eula's content
-
-

Fixing font of Eula’s content and checkbox alignment

---

login-workflow/src/screens/CreateAccountScreen/CreateAccountScreenBase.tsx

Fixes #BLUI-5528 .
- Fixed the [issue](https://github-production-user-asset-6210df.s3.amazonaws.com/133877691/315272885-37ec1590-0be3-459a-ba5c-9d5cb51baa73.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20240329%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240329T105614Z&X-Amz-Expires=300&X-Amz-Signature=20115134f4692520b60d6db461b47d47092ed0419208846766a2bbc37ea4b1ef&X-Amz-SignedHeaders=host&actor_id=130662346&key_id=0&repo_id=262050383)
-
-
-
-
-

Create Account screen: Clicking on the Next button on the keyboard go to the next page without validation

---

login-workflow/example/src/navigation/navigation-drawer.tsx

Fixes #BLUI-5527
-after clicking on finish button of success screen route redirects to home page
-drawer active menu should be Home instead of Registration provider
-
-
-

Updating active Item in the drawer after completion of the registration and come back to the homepage.

---

login-workflow/src/screens/ContactScreen/ContactSupportScreen.tsx

Create styles for Contact support screen

---

login-workflow/src/__tests__/screens/ChangePasswordScreen.test.tsx
login-workflow/src/screens/ChangePasswordScreen/ChangePasswordScreen.tsx

Fixes # BLUI-5113
- Updated change password button labels
- Removed back button
- 
- Open drawer
- Press Auth Provider
-

Updated change password buttons labels

---

login-workflow/example/App.tsx
login-workflow/example/src/components/UserMenuExample.tsx
login-workflow/example/translations/i18n.ts
login-workflow/jestSetupFile.js
login-workflow/src/contexts/AuthContext/i18nAuthInstance.ts
login-workflow/src/contexts/RegistrationContext/i18nRegistrationInstance.ts

Fixes # .
updated to code to support system default language if available
updated the code to save user language preference
-
-
-
-
-
-

update i18n instance

---

login-workflow/docs/customization.md
login-workflow/docs/registration-workflow.md
login-workflow/docs/screens/existing-account-success.md
login-workflow/docs/screens/registration-success.md
login-workflow/docs/screens/success.md
login-workflow/src/screens/SuccessScreen/types.ts

Update custom screen reset data

---

login-workflow/docs/routing.md

Fixes BLUI 5140 .
- This should be merge after https://github.com/etn-ccis/blui-react-native-workflows/pull/457
-
-
-
-
-

Update routing documentation

---

login-workflow/example/App.tsx
login-workflow/example/translations/i18n.ts
login-workflow/src/contexts/AuthContext/i18nAuthInstance.ts
login-workflow/src/contexts/RegistrationContext/i18nRegistrationInstance.ts

Fixes # .
Updated the i18n instance for system language 
-
-
-
-
-
-

fix i18n language picker issue

---

.github/workflows/blui-ci.yml
login-workflow/PUBLISHING.md
login-workflow/README.md

Fixes BLUI-5710.
- add build badge for Github workflow
- remove circleCI references in publish readme
- update blui-ci name space to Build
-
-
-

add build badge & remove reference to circleCI

---

login-workflow/src/components/SetPassword/SetPassword.tsx

Fixes #BLUI-5711 .
- Fixed the bug [455](https://github.com/etn-ccis/blui-react-native-workflows/issues/455)
-
-
- 
-
-

Password Fields not cleared

---

login-workflow/src/screens/LoginScreen/LoginScreenBase.tsx

Fixes #5717
- The "Remember me" checkbox label is overlapping the login button in other languages
-
-
-

 Checkbox label overlapping

---

login-workflow/example/App.tsx
login-workflow/example/translations/i18n.ts
login-workflow/src/contexts/AuthContext/i18nAuthInstance.ts
login-workflow/src/contexts/RegistrationContext/i18nRegistrationInstance.ts

updated fallback language for ios simulator

---

login-workflow/src/screens/CreateAccountScreen/CreateAccountScreen.tsx
login-workflow/src/screens/ForgotPasswordScreen/ForgotPasswordScreen.tsx

Fixes #5712
- Pass onChangeText in emailTextInputProps in ForgotPasswordScreen and CreateAccountScreen
- passed callback onChangeText function is not getting called
-
-
-

OnChange text called

---

login-workflow/docs/routing.md

Fixes #BLUI-5714 .
-
-
-
-
-
-

Doc update as per Demo comments

---

login-workflow/src/components/WorkflowCard/WorkflowCardActions.tsx

Fixes #5713
- Button Lables are cut off in other languages
- The buttons on the left and right should stay the same size as one another 
-
-
-
-

Button labels cut off in other languages

---

.github/workflows/blui-ci.yml

Fixes BLUI-5708.
- remove the release/R31 from ci
-
-
-
-
-

Remove release branch from ci

---

.github/workflows/blui-ci.yml

Add codecov token for upload

---

.github/workflows/blui-ci.yml

Run yarn immutable work directory

---

.github/codecov.yml

Fixes BLUI-5748.
- move codecov.yml to GitHub folder and set the configuration with status checks and use the default PR comment from codecov
-
-
- see this PR for screen shot & calc https://github.com/etn-ccis/blui-react-component-library/pull/883
-
-

Move codecov yaml

---

login-workflow/CHANGELOG.md
login-workflow/package.json

Fixes # BLUI-5777
-Updated peer dependencies to match example's dependencies
- 
-
-

Updated peer dependencies

---

login-workflow/CHANGELOG.md
login-workflow/example/package.json
login-workflow/example/yarn.lock
login-workflow/package.json

Fixes # .
- https://github.com/etn-ccis/blui-react-native-workflows/issues/500
- https://github.com/etn-ccis/blui-react-native-workflows/issues/501
- 
- Version changes for RN component library
-ChangeLog changes
-
-
-

Version & changeLog changes for release

---

login-workflow/CHANGELOG.md

- ChangeLog date change
-
-
-
-
-

Date change in ChangeLog

---

login-workflow/src/__tests__/screens/OktaLoginScreenBase.test.tsx
login-workflow/src/__tests__/screens/__snapshots__/OktaLoginScreenBase.test.tsx.snap

- Unit test cases added for Okta login base screen
-
-
-
- yarn test

Unit tests added for Okta login base screen

---

login-workflow/example/src/navigation/index.tsx
login-workflow/example/src/navigation/navigation-drawer.tsx
login-workflow/example/yarn.lock
login-workflow/src/__tests__/screens/OktaLoginScreen.test.tsx

- Okta fullscreen unit testing
-
-
-
- cd login-workflow 
- yarn test

Okta fullscreen unit testing

---

login-workflow/CHANGELOG.md
login-workflow/package.json

- Release beta version for RN okta login
-
-
-
-
-

RN Okta beta release

---

login-workflow/CHANGELOG.md
login-workflow/package.json

Package version & changelog updated

---

.github/workflows/blui-ci.yml

Fixes # BLUI-6549
-Updated github actions version
-
-
-

Updated github actions version

---

README.md
login-workflow/README.md

Fixes # .
- Message for Archiving Repo
-
-
-
-
-

added archieve repo message to readme
